version: '3'
services:
  juiceshop:
    container_name: juiceshop
    image: bkimminich/juice-shop
    ports:
      - 3000:3000
  waf:
    container_name: waf
    build: ./
    ports:
      - 3001:80
    links:
      - "juiceshop:juiceshop"
    volumes:
      - ./conf:/usr/local/nginx/conf
networks:
  default:
    driver: bridge